# Generated by Django 5.0.3 on 2024-04-01 19:38

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_cryptographickey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cryptographickey',
            unique_together={('user', 'key')},
        ),
        migrations.AddField(
            model_name='cryptographickey',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 4, 1, 19, 38, 52, 62550, tzinfo=datetime.timezone.utc), max_length=256),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cryptographickey',
            unique_together={('user', 'key'), ('user', 'name')},
        ),
    ]
