# Generated by Django 5.0.3 on 2024-04-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_cryptographickey_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptographickey',
            name='key',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='cryptographickey',
            name='name',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
